<?php
return [
	"Sol Campbell",
	"Teddy Sheringham",
	"Freddie Ljungberg",
	"Gary Neville",
	"Frank De Boer",
	"Robbie Fowler",
	"Stefan Effenberg",
	"Filippo Inzaghi",
	"Oliver Bierhoff",
	"Paulo Futre",
	"Hernán Crespo",
	"Pauleta",
	"Gianfranco Zola",
	"Christian Vieri",
	"Henrik Larsson",
	"Michael Owen",
	"Robert Pirès",
	"Andrej Shevchenko",
	"Rui Costa",
	"Patrick Kluivert",
	"Frank Rijkaard",
	"Davor Šuker",
	"David Seaman",
	"Jens Lehmann",
	"Patrick Vieira",
	"Gary Lineker",
	"Fabio Cannavaro",
	"Pavel Nedvěd",
	"Gheorghe Hagi",
	"Fernando Hierro",
	"Edwin van der Sar",
	"Marcel Desailly",
	"George Weah",
	"Ruud van Nistelrooy",
	"Romário",
	"Dennis Bergkamp",
	"Luis Figo",
	"Ruud Gullit",
	"Marco van Basten",
	"Lothar Matthaus",
	"Paulo Maldini",
	"Pele"
]
?>